base_url = "https://146parks.blog"

title = "146 Parks"
description = "My quest to visit all of Washington’s state parks."
default_language = "en"

theme = "zola-es-theme"

compile_sass = true
build_search_index = false

generate_feed = true
feed_filename = "rss.xml"

[markdown]
highlight_code = false
smart_punctuation = true
