base_url = "https://146parks.blog"

title = "146 Parks"
description = "My quest to visit all of Washington’s state parks."
default_language = "en"

theme = "zola-es-theme"

compile_sass = true
build_search_index = true

generate_feed = true
feed_filename = "rss.xml"

[search]
index_format = "elasticlunr_json"

[markdown]
highlight_code = false
smart_punctuation = true

[extra]
mastodon_site_account = "@146parks@ericscouten.social"
mastodon_site_url = "https://ericscouten.social/@146parks"
credits = "by @scouten@ericscouten.social"
hashtags = "#travel #photography #waparks #pnw"
es_site = "146p"
map_clustering = false
article_type = "park blogs"
fathom_site_id = "JFNVYDSS"
plausible_site_id = "146parks.blog"
