[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.13.0"

# The magic for deploying previews of branches.
# We need to override the base url with whatever url Netlify assigns to our
# preview site.  We do this using the Netlify environment variable
# `$DEPLOY_PRIME_URL`.

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

# Using 302 (temporary) redirects because I might someday
# want to have a separate welcome page. We'll see.

[[redirects]]
  from = "/parks"
  to = "/"
  status = 302
  force = true

[[redirects]]
  from = "/parks/index.html"
  to = "/"
  status = 302
  force = true
